### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "de.jcup.asciidoctoreditor.asciidoc.AsiidocConfigFileSupport.calculateResolvedMap(

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#370] opened 2021-09-16 14:48 UTC
From my Eclipse log:

java.lang.NullPointerException: Cannot invoke "de.jcup.asciidoctoreditor.asciidoc.AsiidocConfigFileSupport.calculateResolvedMap(java.util.Map, java.util.List)" because "support" is null
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorAttributesProvider.resolveAttributes(AsciiDoctorAttributesProvider.java:106)
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorAttributesProvider.getCachedAttributes(AsciiDoctorAttributesProvider.java:94)
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorImageProvider.resolveImagesDirPath(AsciiDoctorImageProvider.java:138)
	at de.jcup.asciidoctoreditor.provider.AsciiDoctorImageProvider.getCachedSourceImagesPath(AsciiDoctorImageProvider.java:92)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor.getImagesPathOrNull(AsciiDoctorEditor.java:520)
	at de.jcup.asciidoctoreditor.AsciidoctorEditorOutlineSupport.validate(AsciidoctorEditorOutlineSupport.java:178)
	at de.jcup.asciidoctoreditor.AsciidoctorEditorOutlineSupport.lambda$0(AsciidoctorEditorOutlineSupport.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5106)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

**Comment by de-jcup** [comment] 2021-09-17 08:16
Hello Lars, is this just annoying but it works (it seems to be at eclipse application startup phase) or does it lead to the situation that you cannot use the plugin?

(But of course this should be fixed ...)

**Comment by vogella** [comment] 2021-09-17 08:21
@de-jcup I see this quite a lot in my log, so it seems that this is a regular error. Plug-in still works but my log is full of it. :-/

**Comment by vogella** [comment] 2021-09-17 08:21
I restart frequently, so this might be the reason that I also see it frequently.

**Comment by de-jcup** [comment] 2021-09-17 22:47
A simple guard-close when support is not installed could handle this - but maybe this would have additional side effects (e.g. a asciidoc document is not rendered at the startup etc.) 

So maybe just the time for support object creation should be earlier.

**Comment by de-jcup** [comment] 2022-02-20 19:59
This is a duplicate of #385 which is fixed there, so close this issue

**Closed as completed by de-jcup** 2022-02-20 19:59 UTC
Labels: bug
